spring:
  application:
    name: eureka-server
server:
  port: 1113    
eureka:
  instance:
    hostname: peer3
  client:
    serviceUrl:
      defaultZone: http://peer2:1112/eureka/,http://peer1:1111/eureka/